[package]
name = "dotnet-types"
version = "0.1.0"
edition = "2024"

[dependencies]
dotnetdll = { workspace = true }
gc-arena = { workspace = true }
thiserror = { workspace = true }
arbitrary = { version = "1.3", features = ["derive"], optional = true }

[features]
fuzzing = ["dep:arbitrary"]
