[package]
name = "dotnet-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5", features = ["derive"] }
dotnetdll = "0.1.0"
enum_dispatch = "0.3"
gc-arena = "0.5"
libffi = "5.0.0"
libloading = "0.9.0"
parking_lot = "0.12"