[workspace]
members = [
    "crates/dotnet-types",
    "crates/dotnet-utils",
    "crates/dotnet-value",
    "crates/dotnet-assemblies",
    "crates/dotnet-vm",
    "crates/dotnet-cli",
    "crates/dotnet-macros",
]
resolver = "2"

[workspace.dependencies]
dotnet-types = { path = "crates/dotnet-types" }
dotnet-utils = { path = "crates/dotnet-utils", default-features = false }
dotnet-value = { path = "crates/dotnet-value", default-features = false }
dotnet-assemblies = { path = "crates/dotnet-assemblies" }
dotnet-vm = { path = "crates/dotnet-vm", default-features = false }
dotnetdll = { path = "../dotnetdll", version = "0.1.1" }
gc-arena = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
parking_lot = "0.12"
log = "0.4"
paste = "1.0"
libloading = "0.9.0"
dashmap = "6.1"
crossbeam-channel = "0.5"
libffi = "5.0.0"
clap = { version = "4.5", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
