[workspace]
members = [
    "crates/dotnet-types",
    "crates/dotnet-utils",
    "crates/dotnet-value",
    "crates/dotnet-assemblies",
    "crates/dotnet-vm",
    "crates/dotnet-cli",
]
resolver = "2"
