[package]
name = "dotnet-rs"
version = "0.2.0"
edition = "2021"

[features]
default = ["multithreaded-gc"]
multithreading = ["dep:parking_lot"]
multithreaded-gc = ["multithreading"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
dotnetdll = "0.1.0"
enum_dispatch = "0.3"
gc-arena = "0.5"
libffi = "5.0.0"
libloading = "0.9.0"
parking_lot = { version = "0.12", optional = true }