[package]
name = "dotnet-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
gc-arena = { workspace = true }
parking_lot = { workspace = true, optional = true }
inventory = "0.3"

[features]
default = ["multithreaded-gc"]
multithreading = ["dep:parking_lot"]
multithreaded-gc = ["multithreading"]
