[package]
name = "dotnet-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
gc-arena = "0.5"
parking_lot = { version = "0.12", optional = true }

[features]
default = ["multithreaded-gc"]
multithreading = ["dep:parking_lot"]
multithreaded-gc = ["multithreading"]
