[package]
name = "dotnet-value"
version = "0.1.0"
edition = "2021"

[dependencies]
dotnet-types = { path = "../dotnet-types" }
dotnet-utils = { path = "../dotnet-utils", default-features = false }
gc-arena = "0.5"
dotnetdll = "0.1.1"
enum_dispatch = "0.3"

[features]
default = ["multithreaded-gc"]
multithreaded-gc = ["dotnet-utils/multithreaded-gc"]
