[package]
name = "dotnet-vm"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = { workspace = true }
dotnet-assemblies = { workspace = true }
dotnet-macros = { path = "../dotnet-macros" }
dotnet-types = { workspace = true }
dotnet-utils = { workspace = true, default-features = false }
dotnet-value = { workspace = true, default-features = false }
dotnetdll = { workspace = true }
gc-arena = { workspace = true }
libffi = "5.0.0"
libloading = "0.9.0"
parking_lot = { workspace = true }
phf = "0.13"
thiserror = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

[features]
default = ["multithreaded-gc"]
multithreading = ["dotnet-utils/multithreading"]
multithreaded-gc = ["multithreading", "dotnet-utils/multithreaded-gc", "dotnet-value/multithreaded-gc"]
memory-validation = ["dotnet-value/memory-validation"]

[build-dependencies]
dotnet-macros-core = { workspace = true }
phf_codegen = "0.13"
syn = { version = "2", features = ["full"] }
walkdir = "2"
dotnetdll = { workspace = true }
