[package]
name = "dotnet-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
dotnet-types = { path = "../dotnet-types" }
dotnet-value = { path = "../dotnet-value", default-features = false }
dotnet-assemblies = { path = "../dotnet-assemblies" }
dotnet-utils = { path = "../dotnet-utils", default-features = false }
dotnetdll = "0.1.1"
gc-arena = "0.5"
libffi = "5.0.0"
crossbeam-channel = "0.5"
parking_lot = "0.12"
enum_dispatch = "0.3"
log = "0.4"
paste = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libloading = "0.9.0"
dashmap = "6.1"

[features]
default = ["multithreaded-gc"]
multithreading = ["dotnet-utils/multithreading"]
multithreaded-gc = ["multithreading", "dotnet-utils/multithreaded-gc", "dotnet-value/multithreaded-gc"]
