[package]
name = "dotnet-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
dotnet-types = { workspace = true }
dotnet-value = { workspace = true, default-features = false }
dotnet-assemblies = { workspace = true }
dotnet-utils = { workspace = true, default-features = false }
dotnetdll = { workspace = true }
gc-arena = { workspace = true }
libffi = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
libloading = { workspace = true }
dashmap = { workspace = true }
inventory = "0.3"
dotnet-macros = { path = "../dotnet-macros" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
default = ["multithreaded-gc"]
multithreading = ["dotnet-utils/multithreading"]
multithreaded-gc = ["multithreading", "dotnet-utils/multithreaded-gc", "dotnet-value/multithreaded-gc"]
memory-validation = ["dotnet-value/memory-validation"]
